name: This a workflow title 

on: [push]  # When pushing to any branch then run this action
# Env variable

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: Build the Docker image
          run: docker build .
        